#!bin/bash
if [ $# -eq 0 ]; then
  echo "------No .cpp files supplied"
else
  echo "------COMPILING FILE $1"
  g++ -Wall -Wextra $1 -o a.out
fi

if [ -e "a.out" ]; then
  for i in `seq 1 5`;
  do
    if [ -e "testy/test$i.txt" ] && [ -e "testy/ans$i.txt" ]; then
      echo "------TEST $i"
      var1=$(./a.out < testy/test$i.txt)
      var2=$(cat testy/ans$i.txt)
      if [ "$var1" == "$var2" ]; then
          echo "------CORRECT"
      else
          echo "------SOMETHING IS WRONG! Your output is:"
          echo "$var1"
          echo "------Instead of that should be:"
          echo "$var2"
      fi
    else
        echo "------Files not found!"
    fi

  done
  rm a.out
fi
